2016-12-08 08:18:23.0171|ERROR|  GetHTMLByURL Exception 
2016-12-08 08:19:54.2704|ERROR|  GetHTMLByURL ExceptionSystem.Exception: 这是错误...
   at Dy2018CrawlerWithDB.HTTPHelper.GetHTMLByURL(String url) in C:\code\github\Dy2018CrawlerWithDB\src\Dy2018CrawlerWithDB\Common\HTTPHelper.cs:line 26 
2016-12-08 08:20:12.3535|ERROR|  GetHTMLByURL ExceptionSystem.Exception: 这是错误...
   at Dy2018CrawlerWithDB.HTTPHelper.GetHTMLByURL(String url) in C:\code\github\Dy2018CrawlerWithDB\src\Dy2018CrawlerWithDB\Common\HTTPHelper.cs:line 26 
2016-12-08 08:33:49.9387|ERROR|  GetHTMLByURL ExceptionSystem.AggregateException: One or more errors occurred. (The remote server returned an error: (404) Not Found.) ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Dy2018CrawlerWithDB.HTTPHelper.GetHTMLByURL(String url) in C:\code\github\Dy2018CrawlerWithDB\src\Dy2018CrawlerWithDB\Common\HTTPHelper.cs:line 24
---> (Inner Exception #0) System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)<---
 
2016-12-08 08:34:36.8347|ERROR|  GetHTMLByURL ExceptionSystem.AggregateException: One or more errors occurred. (The remote server returned an error: (404) Not Found.) ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Dy2018CrawlerWithDB.HTTPHelper.GetHTMLByURL(String url) in C:\code\github\Dy2018CrawlerWithDB\src\Dy2018CrawlerWithDB\Common\HTTPHelper.cs:line 24
---> (Inner Exception #0) System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)<---
 
2016-12-08 08:35:00.5412|ERROR|  GetHTMLByURL ExceptionSystem.AggregateException: One or more errors occurred. (The remote server returned an error: (404) Not Found.) ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Dy2018CrawlerWithDB.HTTPHelper.GetHTMLByURL(String url) in C:\code\github\Dy2018CrawlerWithDB\src\Dy2018CrawlerWithDB\Common\HTTPHelper.cs:line 24
---> (Inner Exception #0) System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)<---
 
2016-12-08 08:35:35.9055|ERROR|  GetHTMLByURL ExceptionSystem.AggregateException: One or more errors occurred. (The remote server returned an error: (404) Not Found.) ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Dy2018CrawlerWithDB.HTTPHelper.GetHTMLByURL(String url) in C:\code\github\Dy2018CrawlerWithDB\src\Dy2018CrawlerWithDB\Common\HTTPHelper.cs:line 24
---> (Inner Exception #0) System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)<---
 
